### ISSUE TITLE
Show dialog instead of fragment or activity.

### ISSUE THREAD

**Issue by rajam1215** [maayyaannkk/CountryPicker#3]
Hello @maayyaannkk 

Please use fragment container <Frame Layout> to show all countries in app activity. Not a dialog box or your library screen. please look in to it.

Thanks.

**Comment by maayyaannkk** [comment]
@rajam1215 do you mean something like a custom view that can be embedded in your layout?

**Comment by rajam1215** [comment]
Hello @maayyaannkk 

You can say you need to make view in fragment, and give us container. so we can use this container to show your layout in our layout, i just want you don't use dialog box when click on button, dialog open of country list. I want when screen open all country list open in my layout, not open dialog.

Thanks

Please take reference of this library
https://android-arsenal.com/details/1/6295

you library is very good, it will be awesome, if you do this kind of stuff.

**Comment by rajam1215** [comment]
> @rajam1215 do you mean something like a custom view that can be embedded in your layout?

Hello @maayyaannkk 

You can say, you need to make view in fragment and give a container for layout <Frame Layout>. so we can use this container to show your layout in our layout, i just want you don't use dialog box when click on button, dialog open of country list. I want when screen open all country list open in my layout, not open dialog.

Thanks

Please take reference of this library
https://android-arsenal.com/details/1/6295

you library is very good, it will be awesome, if you do this kind of stuff.

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.scrounger.countrycurrencypicker.sample.MainActivity">

    <FrameLayout
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/button" />

</RelativeLayout>

And  in main activity

CountryCurrencyPicker pickerFragment = CountryCurrencyPicker.newInstance(PickerType.CURRENCYandCOUNTRY, this);

            getSupportFragmentManager().beginTransaction()
                    .replace(R.id.container, pickerFragment).commit();

But you use onActivityResult() method, please look in to it.

**Comment by maayyaannkk** [comment]
hey @rajam1215 check out the new version 1.0.1, I have added new functionality

**Comment by rajam1215** [comment]
> hey @rajam1215 check out the new version 1.0.1, I have added new functionality

Hello  @maayyaannkk 

ERROR: Failed to resolve: com.github.maayyaannkk:CountryPicker:1.0.1
Show in Project Structure dialog
Affected Modules: app

This version show some error when we implement from gadle, you can check with add this dependency in any new dummy project please check you get this error or not. please check.

Thanks

**Comment by maayyaannkk** [comment]
sorry, 1.0.1 cached with some build error, use version 1.0.2 (tested)

**Comment by rajam1215** [comment]
> sorry, 1.0.1 cached with some build error, use version 1.0.2 (tested)

Hello @maayyaannkk 

very good, i appreciate your effort, library is very good now. but i think one enhancement you can do in this library. when you click on country list item, there is no any animation. so how user know country selected or not, need to have select animation like recycler View, i see your code, that is linear layout to show list.

that is good approach, but i think it is want some animation, that user select item or not

Thanks

**Comment by maayyaannkk** [comment]
Thanks for your suggestion, this is done in 1.0.3

**Comment by rajam1215** [comment]
> Thanks for your suggestion, this is done in 1.0.3

Hello @maayyaannkk 

Now library is very fine with proper look and feel. **I close that issue.** please give more enhancement for future, so other developers can use your library with less efforts.

Thanks
